### ISSUE TITLE
Grupos Trabalho 2

### ISSUE THREAD

**Issue by goncalocesar01** [miguelriemoliveira/savi_22-23#10]
Olá Boa tarde
Estamos com dificuldade encontrar um membro para o nosso grupo. Se alguém se quiser juntar a nós, por favor responda a este issue.
Obrigado.

Gonçalo Rodrigues nº98226
Gaspar Soares nº98154

**Comment by JasCosta** [comment]
Olá bom dia, também estou sozinho. Posso juntar a vós.jose Costa 19178

**Comment by goncalocesar01** [comment]
Olá Bom dia podias me mandar o teu numero para criar um grupo de whatsapp

**Comment by JasCosta** [comment]
925892958
