### ISSUE TITLE
trab12/ex1

### ISSUE THREAD

**Issue by JasCosta** [miguelriemoliveira/savi_22-23#11]
Ao correr o main.py do trabalho 12/ex1 
dá a mesg de erro abaixo.

jc@jc:~/Documents/savi_22-23-main/SAVI-master/Parte12/Ex1$ ./main.py
Traceback (most recent call last):
  File "./main.py", line 211, in <module>
    main()
  File "./main.py", line 57, in main
    image_filenames = random.sample(image_filenames, k=400)
  File "/usr/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by miguelriemoliveira** [comment]
Olá José,

imprima a lista image_filenames. Julgo que deve estar vazia, e por isso dá erro a fazer sampling.

Veja o vídeo da aula. Eu tenho um dataset que descarreguei para o disco. Você já descarregou? Ajustou a diretoria

    dataset_path = '/home/mike/savi_datasets/dogs-vs-cats-redux-kernels-edition/train'

 para o seu caso?
