### ISSUE TITLE
Scenes dataset v2 .ply file does not contain color

### ISSUE THREAD

**Issue by TatianaResend** [miguelriemoliveira/savi_22-23#12]
When reading the point cloud of the scenes dataset v2 the .ply file doesn't contain color (1st figure). When trying to open with meshlab it shows a colored pointcloud. I tried to save the pointcloud from meshlab and import it again to o3d but opens a black pointcloud (2nd figure), only after pressing the key L it shows the colored pointcloud (3rd figure).

1st figure
<img src="https://user-images.githubusercontent.com/101273005/209670383-76064d95-f3b3-4348-9376-a0b4e3752e2e.png" width=60% height=60%>

2nd figure
<img src="https://user-images.githubusercontent.com/101273005/209670586-3d5d8221-5675-4968-b329-7f9e2c109ea9.png" width=60% height=60%>

3rd figure
<img src="https://user-images.githubusercontent.com/101273005/209670774-3dbaeaa4-4144-4599-8c6f-f8b5e44931b2.png" width=60% height=60%>

**Comment by miguelriemoliveira** [comment]
Hi @TatianaResend ,

what is your question exactly?

**Comment by TatianaResend** [comment]
When I try to load the scene, it doesn't paint the point cloud. It just paints it with the rainbow colors. But when opening in meshlab everything is fine.
How can I fix this problem?

**Comment by miguelriemoliveira** [comment]
Can you put  here  a MWE https://en.wikipedia.org/wiki/Minimal_reproducible_example ?

**Comment by TatianaResend** [comment]
MWE: https://youtu.be/7fe7e2MypUc

**Comment by fabio-rcs** [comment]
For what I could understand, the problem is the user defined headers on the .ply files:
`property uchar diffuse_red
property uchar diffuse_green
property uchar diffuse_blue`
Found this [issue](https://github.com/mapillary/OpenSfM/issues/741#issuecomment-1183837705) that explained that Open3D doesn't support the 'diffuse_ elements. 
Tried to remove manually these prefixes, but after couldn't open the file. The best solution I found is to export the PointCloud from MeshLab, since it gives headers without the "diffuse_" prefix. Despite I wasn't able to do it, because after exporting and opening in open3D, all the points turned black (don't know why).

Hope I could help.

**Comment by miguelriemoliveira** [comment]
Hi @TatianaResend ,

thanks. Can you add here the original ply so I can try from my side.

Also, if you can please add a script with that code for loading and visualizing.

**Comment by TatianaResend** [comment]
Here is the script: 
[main.zip](https://github.com/miguelriemoliveira/savi_22-23/files/10314124/main.zip)

**Comment by miguelriemoliveira** [comment]
Hi @TatianaResend ,

here's a solution:

First install pcl-tools so you have a script to convert from ply to pcd

    sudo apt-get install pcl-tools

Then you can convert any ply point cloud you want to use to pcd, and after load the pcd format which works great with colors.
```python

    # ------------------------------------------
    # Initialization
    # ------------------------------------------
    print("Load a ply point cloud, print it, and render it")
 
    # point_cloud = o3d.io.read_point_cloud('01.ply')
    point_cloud_filename = '01.ply'
    os.system('pcl_ply2pcd ' + point_cloud_filename + ' pcd_point_cloud.pcd')
    point_cloud = o3d.io.read_point_cloud('pcd_point_cloud.pcd')

    # print(point_cloud.point.diffuse_red)

    o3d.visualization.draw_geometries([point_cloud],
                                    zoom=view['trajectory'][0]['zoom'],
                                    front=view['trajectory'][0]['front'],
                                    lookat=view['trajectory'][0]['lookat'],
                                    up=view['trajectory'][0]['up'])
```

**Comment by TatianaResend** [comment]
Thank you, it worked.
