### ISSUE TITLE
PointCloud points color get/conversion

### ISSUE THREAD

**Issue by fabio-rcs** [miguelriemoliveira/savi_22-23#13]
About issue #12: I tried, but couldn't find any function that allowed to convert the colors of the points. 
Is there any?

I know open3D only reads colors in 0-1 and supposing the color values of the dataset are in 0-255, converting should be easy after getting the color property, but how do I get it?

**Comment by fabio-rcs** [comment]
As issue #12 was solved, this one can be closed to.

**Comment by miguelriemoliveira** [comment]
Hi @fabio-rcs ,

sorry, I did not see this issue. Glad its solved.
