### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by guilherme-mota** [miguelriemoliveira/savi_22-23#14]
Boa noite, professor,

Enquanto estava a realizar o exercício da aula 12, reparei que a propriedade `torch.cuda.is_available( )`, estava sempre a "False".
Pensei que isto estivesse a acontecer, por não ter o driver da placa gráfica instalado. Sendo assim, instalei o driver recomendado pelo Ubuntu.

Desde esse momento, não consigo aceder à internet nem por wifi nem por cabo de rede, e o rato do computador também não funciona.
No entanto, quando corro o comando `lspci` no terminal, aparecem os dois drivers.

Já tentei algumas coisas, como desabilitar o Secure Boot e verificar se o Fast Startup do Windows 10 se encontrava desabilitado, mas nada funcionou.

Será que me pode ajudar?

**Comment by miguelriemoliveira** [comment]
Olá Guilherme,

não sei o que possa ter acontecido. Em último caso terá de reinstalar. 
Tente desinstalar os drivers da gpu que instalou ...

Miguel

**Comment by guilherme-mota** [comment]
Boa noite, professor,

Obrigado.

Tentei uma série de coisas, mas nada funcionou. Acabei por ter de reinstalar o Ubuntu, tal como disse

**Comment by miguelriemoliveira** [comment]
Olá Guilherme.

Pois, quando me acontece isso o melhor é mesmo reinstalar. 

Normalmente tenho três partições para o Linux, uma de root (/) outra de home (/home) e outra de swap.

Assim quando tenho de reinstalar só preciso de formatar e escrever na partição de root e mantenho todos os documentos do home.
