### ISSUE TITLE
Duvidas nos parametros do ICP

### ISSUE THREAD

**Issue by jotadateta** [miguelriemoliveira/savi_22-23#16]
Na aula o professor tambem está a ter o valor de fitness em 1.0 para todas as transformações, o erro que estou a ter é que quando faço as transformações o erro que me dá em alguns objectos sem sentido é menor do que o que deveria ser o real, como tenho abaixo em duas imagens para mostrar de exemplo:
![Screenshot from 2023-01-12 17-29-43](https://user-images.githubusercontent.com/100309502/212138067-0130fa7e-12b0-477c-af59-8dbb8a2b8b34.png)
![Screenshot from 2023-01-12 17-29-54](https://user-images.githubusercontent.com/100309502/212138074-0bf1f929-5750-46a6-8247-5a4025b59bfa.png)

Estou a comparar a caixa de cereais com uma caixa de cereais e tenho um erro aproximado de 0.09 e quando comparado com uma lata de sumo tenho um erro de 0.05, já tive a tentar mexer em todos os possiveis parametros mas como o algoritmo utiliza o numero de pontos que deu match para calcular o erro a lata contem menos e maior percentagem deles com match o que "faz ruido" no algoritmo , o professor ou algum colega tem alguma dica?

@miguelriemoliveira

**Comment by miguelriemoliveira** [comment]
Olá @jotadateta ,

nas imagens o que são os pontos azuis e os amarelos?

Acho que pode calcular ao contrário, quer dizer, em vez de calcular do objeto A em relação ao B, fazê-lo do B em relação ao A.

Assim talvez não tenha esse problema.

**Comment by jotadateta** [comment]
Obrigado professor , coloquei a calcular ao contrário e obtenho valores muito melhores!
