### ISSUE TITLE
Converting 3D coordinates to corresponding pixels of the scene images

### ISSUE THREAD

**Issue by andrefdre** [miguelriemoliveira/savi_22-23#17]
My team was already able to isolate all the objects in the scenes. Now we tackled tacking the coordinates from xyz coordinates to pixels in the images, but can't find a solution. 

Right now, we tried looking into the following:

- Using the camera intrinsic and extrinsic parameters, but we can't obtain this values, at least not automatically. I tried collecting some 3D points and use OpenCV to calibrate the camera with the 2D corresponding points; 
- Also tried looking into projecting the points 3D points into 2D plane and then somehow convert the values into pixels (couldn't find a solution)
- Use feature matching to match 3D points with 2D to calculate the camera parameters.

Maybe we are just looking at the problem in the wrong way, does the teacher @miguelriemoliveira has any suggestion?

**Comment by miguelriemoliveira** [comment]
Hi @andrefdre ,

my idea was to go with your first option.

> Using the camera intrinsic and extrinsic parameters, but we can't obtain this values, at least not automatically. I tried collecting some 3D points and use OpenCV to calibrate the camera with the 2D corresponding points;

Are you sure you cannot find the intrinsics of the camera anywhere in the dataset?

**Comment by andrefdre** [comment]
Hi @miguelriemoliveira,

> Are you sure you cannot find the intrinsics of the camera anywhere in the dataset?

I searched and didn't find anything, but I might overlook it.

**Comment by miguelriemoliveira** [comment]
Search a bit more and send an email to the authors of the dataset.
Perhaps it helps.

**Comment by andrefdre** [comment]
Thanks, I will try to contact the authors and if I get an answer I will share it here for the rest of the students. For now, I will close the issue and if I find something new, I will reopen.

**Comment by miguelriemoliveira** [comment]
ok, thanks.

**Comment by andrefdre** [comment]
Hi @miguelriemoliveira, our team tried contacting the owners of the dataset and didn't get an answer. We also searched for camera information and didn't find anything. We looked into the point cloud and searched for camera information in two ways, using Open3D which always gave 0 in every parameter; And using MeshLab which gave some parameters but when we tried them in the code the results weren't as expected, which suggests that these parameters are wrong. The image below shows white dots that are the object centroids calculated using MeshLab parameters, as seen in the image they are off. After acquiring these results, we tested with the point cloud from class 9 and Meshlab showed the same camera parameters, suggesting it is the default parameters from the program.

![Screenshot from 2023-01-14 14-00-34](https://user-images.githubusercontent.com/58526188/212475967-c5a52391-d535-40ff-b32d-65c47a051d7d.png)

Right now, we can't move forward in the project before solving this problem, what suggestion does the teacher present?

**Comment by miguelriemoliveira** [comment]
Hi @andrefdre ,

I have contacted the washington RGBD dataset people also. Lets give them some time to answer.

In the meantime I think you can improve each of the separate modules, i.e., object detection from point clouds, and object classification from RGB images.

If all goes wrong you will present these two modules separately ... but I still have hope we can find a way.

**Comment by Rafafbo** [comment]
Hi @andrefdre ,
I think what you're looking for is the pose files that comes with the download of the scene dataset. Here, https://rgbd-dataset.cs.washington.edu/dataset/rgbd-scenes-v2/README.txt are the description of the files

**Comment by andrefdre** [comment]
Hi @Rafafbo,

I saw that file, but it only has the camera poses. What we need is camera intrinsic and extrinsic parameters, often obtained by calibrating it with the chess pattern.

**Comment by miguelriemoliveira** [comment]
Hi @Rafafbo ,

I saw those also, but I do not think that they are what we need so I agree with @andrefdre .

We need the intrinsic parameters, meaning the fx,fy, cx and cy.

https://towardsdatascience.com/what-are-intrinsic-and-extrinsic-camera-parameters-in-computer-vision-7071b72fb8ec

**Comment by miguelriemoliveira** [comment]
Hello to all,

I got a response from Dr Kevin Lai indicating the intrinsic parameters of the camera's used in the RGBD dataset.

I copy the conversation below:

> Hi Kevin,
> 
> thank you for the quick reply. That's exactly what we need.
> 
> Also, thank you for making the dataset available to the community.
> 
> Best regards,
> Miguel
 
> 
> On Sun, Jan 15, 2023 at 4:31 PM Kevin Lai <kevin.lai.726@gmail.com> wrote:
> Hi Miguel,
> 
> Thank you for your interest in using the RGB-D Scenes dataset for your computer vision course!
> 
> You can find a MATLAB implementation of going from depth image to point cloud here: https://rgbd-dataset.cs.washington.edu/software/depthToCloud.m which contains the instrinsics and extrinsics that you are looking for.
> 
> Hope this helps.
> Kevin Lai


> On Sun, Jan 15, 2023, 1:15 AM Miguel Armando Riem de Oliveira <mriem@ua.pt> wrote:
> Dear Kevin,
> 
> I am teaching a computer vision course at the university of Aveiro, Portugal.
> 
> The goal in this last assignment is for the students to do a 3D point cloud processing module that detects objects in the Washington RGB-D Scenes dataset point clouds.
> 
> Our idea was to use these segmented point clouds and project them into the RGB image in order to extract a subimage containing only the object, which then could be fed into a network for classification.
> 
> The problem is that in order to project the segmented 3D points into the RGB image we need the RGB intrinsics and the RGB to Depth extrinsics. I searched around in the dataset but could not find this information.
> 
> Could you please share this information?
> 
> Thanks in advance,
> Miguel

I think this solves the problem. Let me know if you have additional problems.

**Comment by andrefdre** [comment]
Hi @miguelriemoliveira,

That's good news. I looked into the file and the line `constant = 570.3;`  raised the question of what does it represent? Is it the focal length? When we tried that value, the projected points weren't correct also, as seen by the white dots not representing the object's centroid. 

![Screenshot from 2023-01-15 19-04-18](https://user-images.githubusercontent.com/58526188/212561674-4cf735e7-f8bd-4f98-b066-8af576bd67be.png)

Also, shouldn't we expect the file to have extrinsic parameters?

**Comment by miguelriemoliveira** [comment]
Hi @andrefdre ,

this is the function to project points in 3D (object points) to pixels.

https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga1019495a2c8d1743ed5cc23fa0daff8c

A projection requires an intrinsic camera matrix like this

![image](https://user-images.githubusercontent.com/11350998/212562224-8b1b926f-8106-4276-8c67-8364aea652c7.png)

From Kevin Lai's code
570.3 is the value of fx and fy.
cx is 320
cy is 240

About the extrinsics, which in the opencv function are represented by the rotation matrix rvec and the translation vector tvec. These are used to geometrically transform an object point into the camera's coordinate frame.
In our case, since the points are 3D points from a point cloud acquired from the depth camera, we would need to transform the points from the depth camera coordinate system into the rgb camera coordinate system.

However, we can consider that the two cameras are near each other and for now assume that this transformation is null, meaning rvec = identity matrix and tvec = [0,0,0].

Remember that the point coordinates have to be in their original frame, if you did some transformation to put them in a better position you have to undo this transformation before you project.

**Comment by andrefdre** [comment]
Thanks for your help I found the problem, I had all the matrixes correct but inverted x with y when drawing in the image.

![Screenshot from 2023-01-15 19-51-24](https://user-images.githubusercontent.com/58526188/212563932-e0b50b75-855d-4365-9cdf-824d7af2d122.png)
![Screenshot from 2023-01-15 19-51-11](https://user-images.githubusercontent.com/58526188/212564030-d755f0af-763e-4981-8ae4-732b98bc4b7c.png)

![Screenshot from 2023-01-15 19-53-59](https://user-images.githubusercontent.com/58526188/212563934-20cbf75b-c7fe-4560-8fd5-405e34f05921.png)

The points have some deviation from the center of the objects (represented with the orange sphere), probably due to the simplification suggested by the teacher, but it is good enough. Thanks to everyone.

**Comment by miguelriemoliveira** [comment]
Great. This is more than sufficient to extract a subimage of only the object. BTW, can you show the boxes around the objects in the image as well?

Another suggestion: you should use more bright colors and bigger markers to note the drawings overlayed on the image. Often I am searching for the markers in the image and points cloud.

Great work.

**Comment by andrefdre** [comment]
Hi, sorry for the delay. 
The results right now: 
![Screenshot from 2023-01-16 16-47-04](https://user-images.githubusercontent.com/58526188/212729625-63b4220a-7c17-44ac-98ec-b4c30cf1a790.png)

It isn't perfect, but we are also giving the points manually from points extracted in the point cloud, and we are having some troubles with using ROS to send this information, that's why I took some time.

Thanks for the suggestions and help.

**Comment by miguelriemoliveira** [comment]
Looks good. Not perfect, but good. Congratullations.

**Comment by guilherme-mota** [comment]
Boa noite, André,

Pelo que percebi, conseguiste utilizar a função [projectPoints](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga1019495a2c8d1743ed5cc23fa0daff8c), sugerida pelo professor.

Eu estou a tentar implementa-la no meu código, no entanto estou a ter alguns problemas.

Para a scene 03, estes são os valores que ela retorna:
```
Image Points:
[[[ 787.94714  123.33589]]

 [[1081.3623   327.00125]]

 [[ 823.46576  253.18813]]

 [[ 720.8827   185.422  ]]]
```

Os argumentos que estou a colocar na função são os seguintes:
```
Centros dos objectos detectados visto do referêncial da camara:
[[ 0.9749159  -0.24305671  1.1881567 ]
 [ 1.3098979   0.14968272  0.98118174]
 [ 1.3818314   0.03619664  1.5652672 ]
 [ 1.0871612  -0.1480111   1.5466071 ]]

rvec:
[[0.]
 [0.]
 [0.]]

tvec:
[0. 0. 0.]

Intrinsic Matrix:
[[570.3   0.  320. ]
 [  0.  570.3 240. ]
 [  0.    0.    1. ]]

distCoeffs:
[0. 0. 0. 0.]
```

Já agora, a minha versão do OpenCV é a 4.7.0.

**Comment by andrefdre** [comment]
Olá @guilherme-mota, eu usei a matriz identidade como matriz rotação. 
Os parâmetros que usei na função project points:

```
# Camera parameters
center = [320 , 240]
focal_length = 570.3

camera_matrix = np.array([[focal_length, 0,            center[0]],
                        [0,            focal_length, center[1]],
                        [0,            0,            1]])
```

```
points_2d = cv2.projectPoints(points, np.identity(3), np.zeros(3), camera_matrix, None,)[0]
```
Se continuares com dúvidas podes ver o meu repositório do trabalho onde tem lá todo o código.

**Comment by guilherme-mota** [comment]
Olá, @andrefdre 

Muito obrigado! 
Assim faremos, caso continuemos com alguma duvida.

Não sei se viste o issue #20, parte do nosso problema estava no facto de estarmos a tentar relacionar uma img RGB da scene 03, com o centro dos objs da scene 05

**Comment by andrefdre** [comment]
Ainda bem que já resolveram o problema, se tiverem mais dúvidas digam.
