### ISSUE TITLE
Presentation of work 2

### ISSUE THREAD

**Issue by TatianaResend** [miguelriemoliveira/savi_22-23#19]
Hi @miguelriemoliveira my group has two questions:
- Can we attend the other groups' presentations? 
- Is there a possibility of the presentation being in person? Since we intend to demonstrate the work also with the use of Kinect in real time, it would be easier in person.

**Comment by miguelriemoliveira** [comment]
Sure you can.

About presenting in person, can it be Tuesday morning, at 11h?

**Comment by TatianaResend** [comment]
Yes it can be on Tuesday at 11am

**Comment by miguelriemoliveira** [comment]
OK, so we meet in person on Tuesday, 31/1 , 11h, at the entrance of the SAVI classroom.
