### ISSUE TITLE
Erro a converter os pontos 3D para a imagem 2D

### ISSUE THREAD

**Issue by guilherme-mota** [miguelriemoliveira/savi_22-23#20]
Boa tarde, professor,

Estamos com algumas dificuldades na conversão dos pontos 3D para a imagem RGB.

Como pode ver pelos valores abaixo, a função _projectPoints_ está a retornar os pontos centrais dos objetos, com as mesmas coordenadas em pixeis, apesar dos valores dos pontos, em relação ao referencial da camara, serem diferentes.

Basicamente, os pontos centrais dos objetos são detectados em relação ao referencial da mesa. Para obter as suas coordenadas em relação ao referencial da camara, multiplicamos pela matriz T_cam_mesa.

```
T_cam_mesa Matrix:
[[ 0.79863551  0.          0.          1.13443391]
 [ 0.         -0.24679194  0.          0.02637907]
 [ 0.          0.         -0.30901699  1.30109879]
 [ 0.          0.          0.          1.        ]]

Intrinsic Matrix:
[[  0.5703   0.     320.    ]
 [  0.       0.5703 240.    ]
 [  0.       0.       1.    ]]

Centros dos objectos detectados visto do referêncial da mesa:
[[-0.28904969 -0.08036985  0.13909398]
 [ 0.21402922 -0.31141004  0.09936275]
 [ 0.20429322  0.28522924  0.0447653 ]
 [-0.141724    0.25801834  0.02059089]]

Centros dos objectos detectados visto do referêncial da camara:
[[ 0.9035886   0.04621371  1.2581164 ]
 [ 1.3053652   0.10323256  1.270394  ]
 [ 1.2975898  -0.0440132   1.2872655 ]
 [ 1.0212481  -0.03729777  1.2947359 ]]

Height: 480, Width: 640

rvec:
[[0.]
 [0.]
 [0.]]

tvec:
[0. 0. 0.]

Image Points:
[[[320.4096  240.02095]]

 [[320.586   240.04634]]

 [[320.57486 239.9805 ]]

 [[320.44983 239.98357]]]

```

**Comment by miguelriemoliveira** [comment]
Olá @guilherme-mota ,


> Como pode ver pelos valores abaixo, a função projectPoints 

Fala da função projectPoints, mas não especifica. Um link ajudava.

> está a retornar os pontos centrais dos objetos, com as mesmas coordenadas em pixeis, apesar dos valores dos pontos, em relação ao referencial da camara, serem diferentes.

Não percebo completamente. Refere-se aos Image Points serem todos iguais?
Do que vejo a vossa matriz intrínseca tem valores estranhos. O fx e o fy normalmente são da ordem das centenas, e.g. 570, você tem 0.570. Será isso?
 
> Basicamente, os pontos centrais dos objetos são detectados em relação ao referencial da mesa. Para obter as suas coordenadas em relação ao referencial da camara, multiplicamos pela matriz T_cam_mesa.

Isto faz sentido. E só depois é que multiplica os pontos 3d, já no referencial da câmara, pela matriz intrínseca de modo a obter os pixeis.

**Comment by guilherme-mota** [comment]
Link para a função _projectPoints_:
https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga1019495a2c8d1743ed5cc23fa0daff8c

Sim, professor, os pontos retornados pela função _projectPoints_ são todos praticamente iguais.

Inicialmente estava a utilizar o valor de 570.3, e os valores que obtia eram ainda mais estranhos, como por exemplo, valores negativos para os pixeis.
Depois converti para metros, pois penso que os pontos do centro dos objetos, detectados na pcd, são também dados em metros.

**Comment by miguelriemoliveira** [comment]
Olá @guilherme-mota ,

mas o fx e o fy não são milímetros para converter para metros. Acho que deve ficar 570.

Quando diz:

> Centros dos objectos detectados visto do referêncial da camara:
> [[ 0.9035886   0.04621371  1.2581164 ]
>  [ 1.3053652   0.10323256  1.270394  ]
>  [ 1.2975898  -0.0440132   1.2872655 ]
>  [ 1.0212481  -0.03729777  1.2947359 ]]

é x, y, z, cada linha um ponto?

Coloque aqui os valores dos Pixels que recebe se usar 570.

**Comment by guilherme-mota** [comment]
Sim, extamente. Em cada linha estão as coordenadas x y z, do centro dos objetos detectados em cima da mesa, vistos do referencial da camara.

```
Intrinsic Matrix:
[[570.3   0.  320. ]
 [  0.  570.3 240. ]
 [  0.    0.    1. ]]

Image Points:
[[[ 784.53644  123.75715]]

 [[1078.6382   330.2296 ]]

 [[ 821.64465  253.64632]]

 [[ 717.8741   186.54189]]]
```

**Comment by miguelriemoliveira** [comment]
Qual é a resolução da sua imagem RGB?

Como obteve a matriz intrínseca da câmara?

**Comment by guilherme-mota** [comment]
Resolução da imagem: 640x480

A matrix intrínseca é criada da seguinte forma:
```
# Intrinsic Matrix
alhpa = 570.3
intrinsic_matrix = np.float32([[alhpa,     0,  320],
                                              [    0,  alhpa, 240],
                                              [    0,      0,       1]])
```
Os valores utilizados são os sugeridos neste [issue](https://github.com/miguelriemoliveira/savi_22-23/issues/17)

**Comment by miguelriemoliveira** [comment]
Pois, do lado dos intrínsecos parece tudo bem.

E em relação a 

> Basicamente, os pontos centrais dos objetos são detectados em relação ao referencial da mesa. Para obter as suas coordenadas em relação ao referencial da camara, multiplicamos pela matriz T_cam_mesa.
> 
> Isto faz sentido. E só depois é que multiplica os pontos 3d, já no referencial da câmara, pela matriz intrínseca de modo a obter os pixeis.

Será que você tem a matriz invertida? Pode tentar multiplicar os pontos da mesa por (T_cam_mesa)-1

**Comment by guilherme-mota** [comment]
Pela inversa obtive estes valores:

```
Image Points:
[[[ 2115.3828  2241.1294]]

 [[-5462.0273 -7314.776 ]]

 [[ 1289.6434  2588.1604]]

 [[ 1293.6859  1906.0947]]]
```

**Comment by miguelriemoliveira** [comment]
Pode fazer-me um favor? Calcule por favor o valor do pixel para um ponto no referencial da câmara de 
xyz = [0,0,1].

Qual é o pixel correspondente?

**Comment by miguelcruz51** [comment]
Professor, 

Envio o pixel correspondente à coordenada [0,0,1] relativa ao referencial da câmara.

```
Centros dos objectos detectados visto do referêncial da camara:
[0.         0.         1.        ]

Image Points:
[[ 320.      240.    ]]
```

**Comment by jotadateta** [comment]
@miguelcruz51  e  @guilherme-mota  Conseguiram solucionar estou com o mesmo problema que voces?

**Comment by guilherme-mota** [comment]
Infelizmente, ainda não conseguimos.

A voces também retorna sempre os mesmo valores?

**Comment by jotadateta** [comment]
@guilherme-mota estamos exatamente iguais , sofremos do mesmo problema que ainda não consegui solucionar , se souber de algo digo logo aqui !

**Comment by guilherme-mota** [comment]
Também vos dá sempre [320 240]? Parece bruxedo

Igualmente, se entretanto conseguirmos resolver, colocamos logo aqui

**Comment by miguelriemoliveira** [comment]
Olá a todos,

Não sei o que se pode passar. Esse teste que o @miguelcruz51 reportou dá o resultado esperado, ou seja, o meio da imagem.

Para mim há duas hipótese:

1. as coordenadas dos vossos pontos não estão corretas, o que pelos valores não parece ser o caso;
2. estão a utilizar incorretamente a função do opencv. Podem colocar aqui o código ou melhor ainda, fazer um script de teste simples para experimentar?

Não sei se consigo voltar a ver os issues hoje. Vou tentar, mas não prometo ...

**Comment by miguelriemoliveira** [comment]
Só mais uma coisa: sei que o André já conseguiu fazer isto https://github.com/miguelriemoliveira/savi_22-23/issues/17, por isso é possível.

Já lhe pediram ajuda?

**Comment by guilherme-mota** [comment]
Olá professor,

Obrigado, pela dica. Era o que devia ter feito logo, vou agora colocar esta questão ao André no issue #17.
Depois vou tentar fazer um código de teste

**Comment by guilherme-mota** [comment]
@jotadateta verifica, por favor, se estas a relacionar a img certa com a tua nuvem de pontos.

No nosso caso estavamos a recolher o centro dos objetos da cena 5 e a tentar relacionar com uma imagem da cena 3...

Fiz essa alteração e obtive estes valores:
```
Image Points:
[[[361.72885 297.11563]]

 [[412.41516 238.33932]]

 [[234.92072 113.80338]]

 [[170.76962 160.69218]]

 [[313.9928  174.13464]]]

```
![image](https://user-images.githubusercontent.com/93254765/215585637-1ceec61a-37b5-404a-84c9-7db3a432ec51.png)

**Comment by miguelriemoliveira** [comment]
A sério? Usar uma nuvem de pontos e a imagem que não lhe corresponde?

Para o ano está comigo a fazer outra vez a UC :)

João,  se o seu problema for o mesmo também está reprovado: )

**Comment by guilherme-mota** [comment]
Foi um fim de semana inteiro a tentar perceber qual o erro, sem sucesso.

Agora implementei o argparse, a ver se não acontece outra vez...
