### ISSUE TITLE
Utilização de pacotes para deteção e reconhecimento

### ISSUE THREAD

**Issue by GoncaloR00** [miguelriemoliveira/savi_22-23#4]
Bom dia,
Durante a realização do trabalho, surgiram várias opções para fazer a deteção e o reconhecimento das caras. Estamos a experimentar usar o opencv, mas também encontramos outros pacotes, já pré-feitos, que conseguem fazer o reconhecimento tão bem ou melhor do que as nossas abordagens e de forma mais eficaz. A nossa questão é se podemos utilizar esse tipo de pacotes e, se sim, se o trabalho será mais valorizado pelo funcionamento e pela fluidez do programa, ou se será pela forma como foi feito.
Obrigado

**Comment by miguelriemoliveira** [comment]
Bom dia,

Podem usar tudo o que quiserem.

Cumprimentos,
Miguel

**Comment by GoncaloR00** [comment]
Obrigado!
Gonçalo Ribeiro
