### ISSUE TITLE
Doubt in TP1

### ISSUE THREAD

**Issue by RSiopa** [miguelriemoliveira/savi_22-23#5]
Good evening,

In TP1, when the professor says "O sistema deverá identificar as pessoas que reconhece, e perguntar sobre as pessoas desconhecidas", does this mean the program must ask who the new people are, ask for their name and add them in the database?

Best regards,
Rafael Siopa

**Comment by miguelriemoliveira** [comment]
Yes, something like that.

**Comment by RSiopa** [comment]
Got it, thank you!
